name = "program-verifications"
version = "0.1.0"
defaultTargets = ["program-verifications"]

[[lean_lib]]
name = "ProgramVerifications"

[[lean_exe]]
name = "program-verifications"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"
